[project]
name = "22-django-master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.9",
    "dotenv>=0.9.9",
    "openai>=2.14.0",
    "pillow>=12.0.0",
    "psycopg2-binary>=2.9.11",
]
